services:
  memoflux:
    build: .
    container_name: memoflux
    env_file:
      - .env
    ports:
      - "8020:8020"
    networks:
      - best-ai-trader_default

networks:
  best-ai-trader_default:
    external: true
